services:
  postgresql:
    image: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: efcore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
